### ISSUE TITLE
getCourses only returns [Object] for each course

### ISSUE THREAD

**Issue by ohashizu** [qwazwsx/infinite-campus#14]
Instead of returning the course information and grades of them, it only returns [Object] for each and every course. 

![Screenshot-461](https://user-images.githubusercontent.com/39673993/128959021-178de051-542a-4e71-b76a-f08a5ee6191b.jpg)

**Comment by qwazwsx** [comment]
This is because Node.JS has a limit on console.log-ing nested objects. For example, if you try the following:
`console.log({a:{b:{c:{d:{e:{f:{g:5}}}}}}})`

it returns:

`{ a: { b: { c: [Object] } } }`

"all is fine until a certain level of nesting. After two levels of nesting, Node.js gives up and prints [Object] as a placeholder:"
-https://nodejs.dev/learn/how-to-log-an-object-in-nodejs

So the data *is* there, console.log just doesn't display it. If you try to `console.log` the specific course (i.e. `.courses[0]`) you should see that the data is there.

If you want to be able to view the data better than in the console, you can try the [Node.JS Inspector](https://nodejs.org/en/docs/guides/debugging-getting-started/) which has no limit on nesting.

**Comment by qwazwsx** [comment]
Another user had a similar problem earlier, please see this comment which explains it in more detail

https://github.com/qwazwsx/infinite-campus/issues/7#issuecomment-786878978

I might add something to the README which explains this better.

**Comment by qwazwsx** [comment]
Closing this because there hasn't been any activity in 10 days.  Please let me know if you have more problems and I can reopen this issue.
