### ISSUE TITLE
Some grades objects are undefined

### ISSUE THREAD

**Issue by Aeiae** [qwazwsx/infinite-campus#16]
Some courses work fine, but others are undefined despite being no different to others. I used the example code from the github page.

**Comment by qwazwsx** [comment]
Hmm... I'm sorry that you are having problems with the API. I'm happy to try and help out.

1. Is there any way you can send me the full output of the courses object so I can debug it? Feel free to anonymize any personal information as you see fit. 

```Javascript
const InfiniteCampus = require('infinite-campus')
const user = new InfiniteCampus('New York District', 'NY', 'JDoe12', 'XXXXXX')

user.on('ready', () => {  
  user.getCourses().then((terms) => {
    console.log(JSON.stringify(terms))
  })
})
```

2. When calling .getCourses() without any parameters do you see the following warning? It may be possible that some courses are classified as a different "school" in infinite campus, this is sometimes the case with online classes.
`WARNING: You are enrolled in x schools, please explicitly specify a school ID to fetch courses`

**Comment by Aeiae** [comment]
I tried to isolate the grades, if this is a bad way of doing it please excuse me because I am new to js.

```
const InfiniteCampus = require('infinite-campus')
// log in                          District Name    State  Username  Password
const user = new InfiniteCampus('XXX', 'XX', 'XXX', 'XX')

// wait until we are done logging in

user.on('ready', () => {
    user.getCourses().then((terms) => {
        for(let i = 0; i < terms[0].courses.length; i++) {
            console.log(JSON.stringify(terms[0].courses[i].grades))
        }
    })
})



// listen for any errors thrown while logging in
user.on('error', (err) => {
    console.log('Error while Logging in. Bad credentials.' + err)
})
```

This prints

```
undefined
undefined
undefined
{"score":"A","percent":98.92,"totalPoints":538.99,"pointsEarned":530.49}
{"score":"A-","percent":94.09,"totalPoints":322,"pointsEarned":303}
undefined
undefined

```
All of my classes have grades, yet only those two work every time I run the program

**Comment by qwazwsx** [comment]
Hm okay. Each instance of Infinite Campus is hosted on its own instance, all with different versions, which makes maintaining this library difficult. Your district's version of I.C. displays data in a slightly different way which is breaking this API.  It's likely that your version uses `class.courseGrades` instead of `class.grades` or some simple naming variation like that. I just need to take a look at how your version outputs data so I can add support for your specific version of I.C.

Could you [download the debug version from here](https://github.com/qwazwsx/infinite-campus/tree/debug), run DEBUG.js, and send me the output? It will output the data directly from the internal I.C. API so I can analyze how this specific version stores grades. Again, feel free to anonymize school names, classes, grades as you see fit. Or, you can always email the output to my personal account here: ![Alfa Zulu India Mike Bravo India November @gmail.com](https://user-images.githubusercontent.com/20545489/140435417-35b8efc3-668b-41d3-a9fe-1fdd81b71164.png)

Also: Does it retrieve all of the courses properly, with just some of the grades missing, or do some courses appear as `undefined`?

Cheers!

**Comment by qwazwsx** [comment]
Tangentially related to https://github.com/qwazwsx/infinite-campus/issues/9#issuecomment-833705686

**Comment by qwazwsx** [comment]
It's been a few weeks since there was any activity in this thread. I was wondering if you wanted to continue debugging this or if you want me to close the issue. I'd love it if we could improve this project by adding support for more versions of I.C. with your debug output, but it's entirely up to you.

Cheers
